version: "3"

services:
  app:
    container_name: wsnotif_app
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    ports:
      - "8999:8999"
    command: "npm run dev"